# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: <%= ENV["INFORMATION_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: information_management_system_production
  username: postgres
  password: <%= ENV["INFORMATION_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: information_management_system_test
  username: postgres
  password: <%= ENV["INFORMATION_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: information_management_system_development
  username: postgres
  password: <%= ENV["INFORMATION_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
